apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask-svc-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask
  type: NodePort
status:
  loadBalancer: {}
